INCLUDE_OPENCCA ?=no

ifeq (${ENABLE_OPENCCA},1)


ARM_ARCH_MAJOR := 8
ARM_ARCH_MINOR := 2


CTX_INCLUDE_PAUTH_REGS := 0
ENABLE_FEAT_CSV2_2 := 0

EL3_EXCEPTION_HANDLING		:=	1
HANDLE_EA_EL3_FIRST_NS		:=	1
ENABLE_SVE_FOR_NS		:=	1


endif # ENABLE_OPENCCA